// Generated by CoffeeScript 1.6.3
(function() {
  var chai, should, strategy;

  strategy = require('..');

  chai = require('chai');

  should = chai.should();

  describe('passport-signature', function() {
    it('should export Strategy constructor directly from package', function() {
      strategy.should.be.a('function');
      return strategy.should.be.equal(strategy.Strategy);
    });
    return it('should export Strategy constructor', function() {
      return strategy.Strategy.should.be.a('function');
    });
  });

}).call(this);
