// Generated by CoffeeScript 1.6.3
/*
 Module dependencies.
*/

var Strategy, exports;

Strategy = require('./strategy');

/*
 Expose `Strategy` directly from package.
*/


exports = module.exports = Strategy;

/*
 Export constructors.
*/


exports.Strategy = Strategy;
