// Generated by CoffeeScript 1.6.3
var BadRequestError,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BadRequestError = (function(_super) {
  __extends(BadRequestError, _super);

  function BadRequestError(message) {
    this.message = message != null ? message : null;
    console.log('Error');
    console.log(BadRequestError.__super__.constructor.apply(this, arguments));
    BadRequestError.__super__.constructor.call(this, message);
    Error.captureStackTrace(this, arguments.callee);
    this.name = 'BadRequestError';
  }

  return BadRequestError;

})(Error);

module.exports = BadRequestError;
